"use client";

import { useEffect, useMemo, useState } from "react";
import { Copy, Download, ExternalLink, FileText, Github, MoreHorizontal, Plus, RefreshCw, Search, Sparkles, Trash2, WandSparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useDashboard, type ReadmeRecord } from "@/features/dashboard/dashboard-context";
import { DashboardShell } from "@/features/dashboard/dashboard-shell";
import { generateMockReadme } from "@/features/readme/mock-readme";

function download(markdown: string) { const url = URL.createObjectURL(new Blob([markdown], { type: "text/markdown" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "README.md"; anchor.click(); URL.revokeObjectURL(url); }
async function copy(text: string) { await navigator.clipboard.writeText(text); }

export function OverviewPage() { const { readmes, repositories } = useDashboard(); return <DashboardShell title="Overview"><div className="dashboard-page"><section className="page-heading"><div><p className="eyebrow">WORKSPACE</p><h1>Good to see you, Dev Lead.</h1><p>Keep your project documentation polished and current.</p></div><Button onClick={() => window.location.assign("/dashboard/generate")}><Sparkles size={16} />GENERATE README</Button></section><section className="stat-grid"><article><small>READMEs CREATED</small><strong>{readmes.length}</strong><span>All time</span></article><article><small>CONNECTED REPOS</small><strong>{repositories.length}</strong><span>Ready to document</span></article><article><small>THIS MONTH</small><strong>{readmes.filter((item) => item.status === "Ready").length}</strong><span>Published drafts</span></article></section><section className="dashboard-panel"><div className="panel-heading"><div><h2>Recent READMEs</h2><p>Your latest documentation work.</p></div><Button variant="outline" onClick={() => window.location.assign("/dashboard/readmes")}>VIEW ALL</Button></div>{readmes.length ? <div className="simple-list">{readmes.slice(0, 4).map((item) => <div key={item.id}><FileText size={19} /><div><strong>{item.name}</strong><small>{item.repository} · {item.updatedAt}</small></div><span className="status-pill">{item.status}</span></div>)}</div> : <Empty text="No READMEs yet. Generate your first one from a repository." action="OPEN GENERATOR" href="/dashboard/generate" />}</section></div></DashboardShell>; }

export function GeneratorPage() { const { saveReadme, notify } = useDashboard(); const [url, setUrl] = useState(""); const [markdown, setMarkdown] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  useEffect(() => { const repository = new URLSearchParams(window.location.search).get("repository"); if (repository) setUrl(repository); }, []);
  function generate() { if (!/^https:\/\/github\.com\/[^/]+\/[^/]+/i.test(url)) { setError("Enter a valid GitHub repository URL."); return; } setError(""); setLoading(true); window.setTimeout(() => { const content = generateMockReadme(url); const name = url.replace(/\/$/, "").split("/").at(-1) ?? "README"; setMarkdown(content); saveReadme({ id: `readme-${Date.now()}`, name, repository: url, updatedAt: "Just now", markdown: content, status: "Ready" }); setLoading(false); }, 650); }
  return <DashboardShell title="Generator"><div className="generator-workspace"><section className="generator-form"><div className="dashboard-section-heading"><span>REPOSITORY CONTEXT</span><i /></div><label>GitHub Repository URL<input value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://github.com/owner/repository" onKeyDown={(event) => { if (event.key === "Enter") generate(); }} /></label><p className="generator-help">Connect a public repository now. AI generation will be wired into this workflow later.</p>{error && <p className="generator-message generator-message--error">{error}</p>}<Button className="generate-button" disabled={loading} onClick={generate}><WandSparkles size={18} />{loading ? "PREPARING README..." : "GENERATE README"}</Button></section><section className="preview-area"><header className="preview-toolbar"><strong>LIVE PREVIEW</strong>{markdown && <div className="preview-actions"><button onClick={() => void copy(markdown).then(() => notify("README copied."))}><Copy size={18} />COPY</button><Button className="export-button" onClick={() => download(markdown)}><Download size={18} />DOWNLOAD .MD</Button></div>}</header>{loading ? <Skeleton /> : markdown ? <textarea className="readme-editor" value={markdown} onChange={(event) => setMarkdown(event.target.value)} aria-label="README Markdown" /> : <Empty text="Your generated README will appear here." icon={<Sparkles size={28} />} />}</section></div></DashboardShell>; }

export function ReadmesPage() { const { readmes, deleteReadme, saveReadme, notify } = useDashboard(); const [query, setQuery] = useState(""); const [sort, setSort] = useState("Recent"); const visible = useMemo(() => readmes.filter((item) => `${item.name} ${item.repository}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => sort === "Name" ? a.name.localeCompare(b.name) : b.id.localeCompare(a.id)), [query, readmes, sort]); return <DashboardShell title="My READMEs"><div className="dashboard-page"><section className="page-heading"><div><p className="eyebrow">DOCUMENTATION</p><h1>My READMEs</h1><p>Search, export, and improve your documentation.</p></div><Button onClick={() => window.location.assign("/dashboard/generate")}><Plus size={16} />NEW README</Button></section><div className="toolbar"><label><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search READMEs" /></label><select value={sort} onChange={(event) => setSort(event.target.value)}><option>Recent</option><option>Name</option></select></div><section className="dashboard-panel">{visible.length ? <div className="readme-table">{visible.map((item) => <article key={item.id}><FileText size={22} /><div><h2>{item.name}</h2><p>{item.repository}</p><small>{item.updatedAt} · {item.status}</small></div><div className="table-actions"><button aria-label="Copy" onClick={() => void copy(item.markdown).then(() => notify("README copied."))}><Copy size={17} /></button><button aria-label="Download" onClick={() => download(item.markdown)}><Download size={17} /></button><button aria-label="Regenerate" onClick={() => { saveReadme({ ...item, updatedAt: "Regenerated just now" }); notify("README queued for regeneration."); }}><RefreshCw size={17} /></button><button aria-label="Delete" onClick={() => deleteReadme(item.id)}><Trash2 size={17} /></button></div></article>)}</div> : <Empty text={query ? "No README matches that search." : "Your README history is empty."} action="GENERATE README" href="/dashboard/generate" />}</section></div></DashboardShell>; }

export function RepositoriesPage() { const { repositories, connectRepository, notify } = useDashboard(); const [url, setUrl] = useState(""); const [query, setQuery] = useState(""); const [selected, setSelected] = useState(repositories[0]?.id ?? ""); const visible = repositories.filter((item) => `${item.name} ${item.fullName}`.toLowerCase().includes(query.toLowerCase())); const active = repositories.find((item) => item.id === selected); function connect() { const result = connectRepository(url); if (result) { setSelected(result.id); setUrl(""); } else notify("Enter a valid GitHub repository URL."); } return <DashboardShell title="Repositories"><div className="dashboard-page"><section className="page-heading"><div><p className="eyebrow">GITHUB</p><h1>Repositories</h1><p>Connect projects and create documentation in one place.</p></div><Button onClick={connect}><Github size={16} />CONNECT GITHUB</Button></section><div className="connect-row"><input value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://github.com/owner/repository" /><Button variant="outline" onClick={connect}>CONNECT</Button></div><div className="repo-layout"><section className="dashboard-panel"><div className="toolbar"><label><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search repositories" /></label><button className="icon-button" onClick={() => notify("Repository list refreshed.")}><RefreshCw size={18} /></button></div><div className="repo-list">{visible.map((item) => <button className={selected === item.id ? "repo-row repo-row--active" : "repo-row"} key={item.id} onClick={() => setSelected(item.id)}><Github size={18} /><span><strong>{item.name}</strong><small>{item.fullName}</small></span><MoreHorizontal size={18} /></button>)}</div></section><section className="dashboard-panel repo-detail">{active ? <><span className="language-tag">{active.language}</span><h2>{active.name}</h2><p>{active.description}</p><small>{active.fullName} · {active.updatedAt}</small><Button onClick={() => window.location.assign(`/dashboard/generate?repository=${encodeURIComponent(`https://github.com/${active.fullName}`)}`)}><Sparkles size={16} />GENERATE README</Button><a href={`https://github.com/${active.fullName}`} target="_blank"><ExternalLink size={15} />OPEN ON GITHUB</a></> : <Empty text="Select a repository to view its details." />}</section></div></div></DashboardShell>; }

export function SettingsPage() { const { preferences, updatePreferences, notify } = useDashboard(); const [form, setForm] = useState(preferences); function update<K extends keyof typeof form>(key: K, value: typeof form[K]) { setForm((current) => ({ ...current, [key]: value })); } return <DashboardShell title="Settings"><div className="dashboard-page settings-page"><section className="page-heading"><div><p className="eyebrow">WORKSPACE</p><h1>Settings</h1><p>Manage your account and documentation preferences.</p></div><Button onClick={() => { updatePreferences(form); notify("Settings saved."); }}>SAVE CHANGES</Button></section><section className="dashboard-panel settings-section"><h2>Profile</h2><div className="avatar-editor"><span>{form.name.slice(0, 1)}</span><Button variant="outline" onClick={() => notify("Avatar uploads will be available with account storage.")}>CHANGE AVATAR</Button></div><div className="settings-grid"><label>Name<input value={form.name} onChange={(event) => update("name", event.target.value)} /></label><label>Email<input type="email" value={form.email} onChange={(event) => update("email", event.target.value)} /></label></div></section><section className="dashboard-panel settings-section"><h2>Appearance</h2><div className="settings-grid"><label>Theme<select value={form.theme} onChange={(event) => update("theme", event.target.value as typeof form.theme)}><option value="dark">Dark</option><option value="system">System</option></select></label><label>Accent color<select value={form.accent} onChange={(event) => update("accent", event.target.value as typeof form.accent)}><option value="violet">Violet</option><option value="green">Green</option></select></label></div></section><section className="dashboard-panel settings-section"><h2>AI Preferences</h2><div className="settings-grid"><label>Model<select value={form.model} onChange={(event) => update("model", event.target.value as typeof form.model)}><option>Balanced</option><option>Fast</option><option>Detailed</option></select></label><label className="switch-row">Include badges<input type="checkbox" checked={form.includeBadges} onChange={(event) => update("includeBadges", event.target.checked)} /><i /></label></div></section><section className="dashboard-panel settings-section danger-zone"><h2>Account</h2><Button variant="outline" onClick={() => { window.localStorage.removeItem("devreadme-state"); window.location.assign("/"); }}>LOG OUT</Button></section></div></DashboardShell>; }

function Empty({ text, action, href, icon }: Readonly<{ text: string; action?: string; href?: string; icon?: React.ReactNode }>) { return <div className="dashboard-empty">{icon ?? <FileText size={27} />}<p>{text}</p>{action && href && <Button onClick={() => window.location.assign(href)}>{action}</Button>}</div>; }
function Skeleton() { return <div className="skeleton"><i /><i /><i /><i /></div>; }
